added envoy proxy prometheus metrics dashboard
GoogleCloudPlatform/monitoring-dashboard-samples pull request #250
Opened 2022-08-18 20:30 UTC by algchoo

* added dashboard json for envoy proxy prometheus metrics 
* included screenshots 
* included readme

2022-08-23 17:41 UTC, EvanSimpson requested changes
@algchoo It looks like my comments on the Apache Airflow and RabbitMQ dashboard PRs are also applicable here and elsewhere. Can you update your PRs to make sure they follow the contribution guidelines?

2022-08-24 17:54 UTC, algchoo commented
> @algchoo It looks like my comments on the Apache Airflow and RabbitMQ dashboard PRs are also applicable here and elsewhere. Can you update your PRs to make sure they follow the contribution guidelines?

@EvanSimpson Thank you for the feedback, I've gone through and made changes to each PR submitted. Please let me know if there is anything else that needs to be changed and I hope you have a great day!

2022-08-25 14:05 UTC, EvanSimpson requested changes

2022-08-25 14:05 UTC, EvanSimpson commented on dashboards/envoy-proxy/metadata.yaml
> +    id: envoy-proxy
```suggestion
    id: envoy-proxy-prometheus
```

2022-08-25 14:05 UTC, EvanSimpson commented on dashboards/envoy-proxy/metadata.yaml
> +        platform: GCE
```suggestion
        platform: GKE
```

2022-08-25 14:06 UTC, EvanSimpson commented
@algchoo Thanks for making the changes! I'll be going through and leaving any more suggestions, as needed.

2022-08-29 17:58 UTC, EvanSimpson approved these changes

2022-08-29 17:58 UTC, merged