added k8s pod/cluster prometheus metrics dashboards
GoogleCloudPlatform/monitoring-dashboard-samples pull request #268
Opened 2022-08-18 20:50 UTC by algchoo

* added dashboard json for k8s pod/cluster prometheus metrics
* included screenshots
* included readme

2022-08-25 15:17 UTC, EvanSimpson requested changes
Can you also update the folder name to be `kubernetes` instead of `k8s`?

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/metadata.yaml
> +        platform: GCE
```suggestion
        platform: GKE
```

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/metadata.yaml
> +        platform: GCE
```suggestion
        platform: GKE
```

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/metadata.yaml
> +    id: kubernetes-pod-overview
```suggestion
    id: k8s-pod-prometheus
```

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/metadata.yaml
> +    id: kubernetes-cluster-overview
```suggestion
    id: k8s-cluster-prometheus
```

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/k8s-cluster-prometheus.json
> +                  "prometheusQuery": "sum by (cluster) (kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
```suggestion
                  "prometheusQuery": "sum by (cluster) (kube_node_status_condition{condition=\"Ready\",status=\"false\"})"
```

2022-08-25 15:17 UTC, EvanSimpson commented on dashboards/k8s/k8s-cluster-prometheus.json
> +              }
These have the same threshold, should there be different values, or can one be removed?

2022-08-29 15:41 UTC, algchoo commented
@EvanSimpson Thanks for the review! I've pushed changes for the feedback in regards to the IDs/filenames needing to match, as well as fixing any mistakes/issues with the dashboard json. I tested importing the json after making those changes and it worked in each case. Hope you're having a great day!

2022-08-29 18:33 UTC, EvanSimpson requested changes
Thanks for all the changes! I've merged a number of the prometheus dashboards, and just have a couple of changes requested on the remaining open ones.

2022-08-29 18:33 UTC, EvanSimpson commented on dashboards/kubernetes/metadata.yaml
> +        platform: GCE
```suggestion
        platform: GKE
```

2022-08-29 18:33 UTC, EvanSimpson commented on dashboards/kubernetes/metadata.yaml
> +        platform: GCE
```suggestion
        platform: GKE
```

2022-08-29 18:33 UTC, EvanSimpson commented on dashboards/kubernetes/k8s-cluster-prometheus.json
> +                  "prometheusQuery": "sum by (cluster) (kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
Carrying this comment forward - should this have a status value of `false`?

2022-08-29 21:16 UTC, EvanSimpson approved these changes

2022-08-29 21:16 UTC, merged