Add filtered dashboards for GKE per-cluster, node, workload views
GoogleCloudPlatform/monitoring-dashboard-samples pull request #270
Opened 2022-08-19 18:33 UTC by yqlu

2022-08-22 18:32 UTC, EvanSimpson requested changes

2022-08-22 18:32 UTC, EvanSimpson commented on dashboards/compute/gke-compute-resources-workload-view.json
> +  "name": "projects/180739612668/dashboards/693f745f-fab1-40c1-9f99-c97507e1c10c"
Can you remove this line?

2022-08-23 15:02 UTC, yqlu commented on dashboards/compute/gke-compute-resources-workload-view.json
> +  "name": "projects/180739612668/dashboards/693f745f-fab1-40c1-9f99-c97507e1c10c"
Good catch, done

2022-08-23 15:20 UTC, EvanSimpson approved these changes

2022-08-23 15:55 UTC, merged