GMP Documentation: MySQL
GoogleCloudPlatform/monitoring-dashboard-samples pull request #365
Opened 2022-11-21 19:43 UTC by jsirianni

This PR adds documentation configuration for the MySQL GMP integration.

-  Added documentation.yaml
-  Added prometheus_metadata.yaml

2022-11-28 17:59 UTC, mtabasko requested changes
Just a couple nits. Thanks!!

2022-11-28 17:59 UTC, mtabasko commented on integrations/mysql/documentation.yaml
> +exporter_name: the Mysql exporter
the MySQL exporter

2022-11-28 17:59 UTC, mtabasko commented on integrations/mysql/documentation.yaml
> +  See the exporter [Required Grants](https://github.com/prometheus/mysqld_exporter#required-grants){:class=external}
For information about creating a least-privileged user, see the exporter [Required Grants](https://github.com/prometheus/mysqld_exporter#required-grants){:class=external} documentation.


(We're supposed to tell users "why" before "what".)

2022-11-29 17:27 UTC, yqlu approved these changes

2022-11-29 19:29 UTC, mtabasko approved these changes

2022-11-29 20:51 UTC, EvanSimpson approved these changes

2022-11-29 20:51 UTC, merged