GMP Documentation and alert: Elasticsearch
GoogleCloudPlatform/monitoring-dashboard-samples pull request #371
Opened 2022-11-29 19:14 UTC by jsirianni

This PR adds documentation configuration for the Elasticsearch GMP integration.

-  Added documentation.yaml
-  Added prometheus_metadata.yaml

The documentation yaml includes an alert ported from https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/tree/master/alerts/elasticsearch-gke

2022-11-29 21:04 UTC, EvanSimpson requested changes

2022-11-29 21:04 UTC, EvanSimpson commented on integrations/elasticsearch/prometheus_metadata.yaml
> +    exporter_metadata:
Can you add a characteristic metric detection as well?

2022-11-29 23:36 UTC, yqlu approved these changes
👍  in terms of validating the config on a cluster myself

Tagging in @mtabasko to review the docs format. This is probably significant in the sense that it is our first "standalone" type exporter doc, so we want to ensure the template works.

2022-11-30 04:38 UTC, mtabasko commented on integrations/elasticsearch/documentation.yaml
> +additional_prereq_info: |
This seems like "additional_install_info" (it makes sense after you've seen the install config).

2022-11-30 04:42 UTC, mtabasko commented
Other than the one small change, from "additional_prereq_info" to "additional_install_info", I don't see any problems. (We had actually done a version of Elasticsearch as a "standalone" exporter when building the template originally -- the biggest diff between "standalone" and "sidecar" in terms of the template is whether we use "config_mods" or "standalone_config" for the config info, and that all looks good here to me! Thanks.

2022-11-30 17:36 UTC, mtabasko approved these changes
docs look good. Thanks again!

2022-12-01 19:23 UTC, EvanSimpson approved these changes

2022-12-01 19:23 UTC, merged