Add GMP Rabbitmq doc
GoogleCloudPlatform/monitoring-dashboard-samples pull request #388
Opened 2022-12-02 17:00 UTC by jsirianni

This PR adds documentation configuration for the Rabbitmq GMP integration.

-  Added documentation.yaml
-  Added prometheus_metadata.yaml

The documentation yaml includes an alert ported from https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/tree/master/alerts/rabbitmq-gke

2022-12-05 14:53 UTC, varun-c reviewed
The prometheus_metadata.yaml looks good. Will defer to YQ for the documentation.yaml file.

2022-12-05 14:53 UTC, varun-c commented on integrations/rabbitmq/prometheus_metadata.yaml
> +    default_metrics:
I noticed that the dashboard that uses this integration uses a rabbitmq_identity_info query. Is that something we should include in this list?

2022-12-06 16:13 UTC, yqlu commented on integrations/rabbitmq/documentation.yaml
> +  will contain the label `app.kubernetes.io/component: rabbitmq` and `prometheus` port.
This is great -- I tested these docs by installing RabbitMQ a different way (via [GCP click-to-deploy](https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/k8s/rabbitmq)) and it had [a different label](https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/chart/rabbitmq/templates/statefulset.yaml#L7), but this was good enough to guide me to adapt the config accordingly.

2022-12-06 21:30 UTC, mtabasko requested changes

2022-12-06 21:30 UTC, mtabasko commented on integrations/rabbitmq/documentation.yaml
> +  Ensure that the values of the port and matchLabels match that of the {{app_name_short}} pods you want to monitor.
\`port\` and \`matchLabels\` fields match those of

(literal "port" and "matchLabels", add "fields", and there's more than one, so "match those", not "match that".

2022-12-06 21:30 UTC, mtabasko commented on integrations/rabbitmq/documentation.yaml
> +  have to install it separately. To verify that {{exporter_name}} is emitting metrics on the expected
This is a little misleading: To verify that ...., set up port-forwarding with the following command". Setting up port forwarding doesn't verify that the metrics are emitted -- it's part of it, but not the whole thing.

The line  "To determine if ..., run the following command" is similarly confusing -- that just sets up port forwarding.

What about something like this:

To verify that {{exporter_name}} is emitting metrics on the expected endpoints, do the following:

0. Set up port forwarding by using the following command: (lines 17-19)
0. Access the endpoint \`localhost:15692/metrics\` by using the browser or the \`curl\` utility in another terminal session.

2022-12-06 21:30 UTC, mtabasko commented on integrations/rabbitmq/documentation.yaml
> +  Access the endpoint `localhost:15692/metrics` by using the browser or curl in another terminal session
the \`curl\` utility

2022-12-06 21:30 UTC, mtabasko commented on integrations/rabbitmq/documentation.yaml
> +  to verify that the metrics are being exposed by the exporter for scraping.
This is a bit redundant with lines 11-12. I think I'd just end this wtih "terminal session."

2022-12-07 16:47 UTC, yqlu approved these changes

2022-12-07 18:58 UTC, mtabasko approved these changes
Looks good to me. Thanks!!

2022-12-07 19:56 UTC, merged