Add Filestore monitoring dashboard integration
GoogleCloudPlatform/monitoring-dashboard-samples pull request #456
Opened 2023-01-17 13:58 UTC by dadeeb

Add Filestore monitoring dashboard integration to cloud monitoring.

2023-01-17 20:00 UTC, varun-c requested changes
The png file is not an image - please upload an image of how the dashboard is supposed to look once setup correctly.

2023-01-17 20:00 UTC, varun-c commented on dashboards/google-filestore/metadata.yaml
> +    id: filestore
This should be the id of the sample_dashboard. In this case, that is `filestore_dashboard`.

2023-01-17 20:00 UTC, varun-c commented on dashboards/google-filestore/filestore_dashbard.json
> +{
The filename has a typo that needs to be fixed for it to correctly show up in the UI.

2023-01-17 20:08 UTC, varun-c commented on dashboards/google-filestore/filestore_dashbard.json
> +{
The json should also exclude the "etag" and "name" fields.

2023-01-18 09:32 UTC, dadeeb commented
Replaced the png file with a working png.
Removed "etag" & "name" from the json file.
Fixed metadata.yaml header to filestore_dashboard.

PTAL

2023-01-18 14:14 UTC, varun-c commented on dashboards/google-filestore/metadata.yaml
> +    id: filestore
My bad, this comment is confusing. On line 1, the field should still be `sample_dashboards`. On this line, the id should be the name of the sample dashboard being added (i.e. `filestore_dashboard`).

2023-01-18 14:15 UTC, varun-c approved these changes
Took another look and have one comment. The PR can be merged once that is resolved.

2023-01-18 14:43 UTC, dadeeb commented
PTAL

2023-01-18 14:49 UTC, varun-c commented
LGTM - merging it.

2023-01-18 14:49 UTC, merged