Redis dashboard KPI and layout updates
GoogleCloudPlatform/monitoring-dashboard-samples pull request #670
Opened 2024-01-09 14:14 UTC by algchoo

This is a first pass at updating the layout for the redis prometheus dashboard, as well as including new KPIs.

### Changes
* Updated the layout to align more with what exists in the style guide
* Added a few useful KPIs to the dashboard

2024-01-31 21:11 UTC, varun-c requested changes
Added some suggestions to apply the template variables to the newly added chart widgets similar to how it is applied to the previously existing widgets.

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_blocked_clients",
```suggestion
                  "prometheusQuery": "redis_blocked_clients{${Cluster}, ${Location}, ${Namespace}}",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_keyspace_hits_total / (redis_keyspace_hits_total + redis_keyspace_misses_total)",
```suggestion
                  "prometheusQuery": "redis_keyspace_hits_total{${Cluster}, ${Location}, ${Namespace}} / (redis_keyspace_hits_total{${Cluster}, ${Location}, ${Namespace}} + redis_keyspace_misses_total{${Cluster}, ${Location}, ${Namespace}})",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_slowlog_length",
```suggestion
                  "prometheusQuery": "redis_slowlog_length{${Cluster}, ${Location}, ${Namespace}}",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_latency_percentiles_usec * 0.001",
```suggestion
                  "prometheusQuery": "redis_latency_percentiles_usec{${Cluster}, ${Location}, ${Namespace}} * 0.001",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_evicted_keys_total",
```suggestion
                  "prometheusQuery": "redis_evicted_keys_total{${Cluster}, ${Location}, ${Namespace}}",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_mem_fragmentation_ratio",
```suggestion
                  "prometheusQuery": "redis_mem_fragmentation_ratio{${Cluster}, ${Location}, ${Namespace}}",
```

2024-01-31 21:11 UTC, varun-c commented on dashboards/redis/redis-prometheus.json
> +                  "prometheusQuery": "redis_client_recent_max_input_buffer_bytes",
```suggestion
                  "prometheusQuery": "redis_client_recent_max_input_buffer_bytes{${Cluster}, ${Location}, ${Namespace}}",
```

2024-02-29 15:18 UTC, varun-c approved these changes

2024-02-29 15:19 UTC, merged

2024-02-29 15:27 UTC, robinreneemac727 commented
I’m just go in and block everything and everyone on this site. I absolutely
did not sign up for any of it. I’m not techie

On Thu, Feb 29, 2024 at 9:19 AM Varun Chandramouli ***@***.***>
wrote:

> Merged #670
> <https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/pull/670>
> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/pull/670#event-11967580018>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYHSMFE7HKKERMJE2DKDLWLYV5DHPAVCNFSM6AAAAABBTFHV3SVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRHE3DONJYGAYDCOA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID:
> <GoogleCloudPlatform/monitoring-dashboard-samples/pull/670/issue_event/11967580018
> @github.com>
>