Add GKE DPv2 observability dashboards
GoogleCloudPlatform/monitoring-dashboard-samples pull request #695
Opened 2024-02-12 15:32 UTC by siwiutki

2024-02-14 11:35 UTC, marqc requested changes

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/metadata.yaml
> +    description: "This dashboard features 6 charts with overview data about the pod-to-workload traffic in your GKE cluster. Monitor how much of your traffic is dropped, see what are the most common
```suggestion
    description: "This dashboard features 6 charts with overview data about the pod-to-workload traffic in your GKE cluster. Monitor how much of your traffic is dropped, see what are the most common drop reasons, all at a glance. [Dataplane V2 metrics must be enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability) to make use of this dashboard."
```

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/metadata.yaml
> +    description: "This dashboard features 4 charts providing pod-to-workload traffic data that is groupable and filterable, letting you gain more detailed insight into the traffic within your GKE clu
```suggestion
    description: "This dashboard features 4 charts providing pod-to-workload traffic data that is groupable and filterable, letting you gain more detailed insight into the traffic within your GKE cluster. Understand which workloads generate the most traffic, drill down which pods drop traffic and what's the reason, and more. [Dataplane V2 metrics must be enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability) to make use of this dashboard."
```

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/README.md
> +|This dashboard features 4 charts providing pod-to-workload traffic data that is groupable and filterable, letting you gain more detailed insight into the traffic within your GKE cluster. Understand
```suggestion
|This dashboard features 4 charts providing pod-to-workload traffic data that is groupable and filterable, letting you gain more detailed insight into the traffic within your GKE cluster. Understand which workloads generate the most traffic, drill down which pods drop traffic and what's the reason, and more. [Dataplane V2 metrics must be enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability) to make use of this dashboard.|
```

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/README.md
> +|This dashboard features 6 charts with overview data about the pod-to-workload traffic in your GKE cluster. Monitor how much of your traffic is dropped, see what are the most common drop reasons, all
```suggestion
|This dashboard features 6 charts with overview data about the pod-to-workload traffic in your GKE cluster. Monitor how much of your traffic is dropped, see what are the most common drop reasons, all at a glance. [Dataplane V2 metrics must be enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability) to make use of this dashboard.|
```

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-cluster-flows-overview.json
> +            "content": "A _flow_ is generated and measured when the eBPF program observes a network packet with a given tuple of (source ip, source port, destination ip, destination port, tcp flags,
```suggestion
            "content": "A _flow_ is generated and measured when the eBPF program (on each node) observes a network packet with a given tuple of (source ip, source port, destination ip, destination port, tcp flags, protocol) and there was no event with exactly the same tuple of these properties within the last five seconds.",
```

2024-02-14 11:35 UTC, marqc commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-drilldown-view.json
> +            "content": "A _flow_ is generated and measured when the eBPF program observes a network packet with a given tuple of (source ip, source port, destination ip, destination port, tcp flags,
```suggestion
            "content": "A _flow_ is generated and measured when the eBPF program (on each node) observes a network packet with a given tuple of (source ip, source port, destination ip, destination port, tcp flags, protocol) and there was no event with exactly the same tuple of these properties within the last five seconds.",
```

2024-02-14 11:56 UTC, marqc approved these changes
lgtm

2024-02-14 19:18 UTC, pintofloyed commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-cluster-flows-overview.json
> +  "etag": "51a3c4a0f285f7738a6d04662347d927",
The etag needs to be removed

2024-02-15 10:02 UTC, siwiutki commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-cluster-flows-overview.json
> +  "etag": "51a3c4a0f285f7738a6d04662347d927",
Done.

2024-02-15 19:18 UTC, siwiutki commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-cluster-flows-overview.json
> +    "legacyRows": 58
Sure, removed these fields

2024-02-15 20:04 UTC, pintofloyed commented on dashboards/google-kubernetes-engine/gke-dpv2-observability-cluster-flows-overview.json
> +    ],
These trailing commas on line 320 and 321 are causing errors in the template. Similar case with the other file

2024-02-16 16:37 UTC, pintofloyed approved these changes

2024-02-16 16:37 UTC, merged