migration of gce-disk dashboard from legacy to sample repo
GoogleCloudPlatform/monitoring-dashboard-samples pull request #802
Opened 2024-07-26 17:23 UTC by philshin-google

added in metadata and config files for gce-disk dashboard.

2024-08-14 18:24 UTC, varun-c approved these changes

2024-08-14 18:24 UTC, varun-c commented on dashboards/google-gce-disk/gce-disk.json
> +          "title": "disk bytes used",
```suggestion
          "title": "Disk bytes used",
```

Should the title be sentence case?

2024-08-14 18:24 UTC, varun-c commented on dashboards/google-gce-disk/metadata.yaml
> +    display_name: Disks
Should we add a description for the dashboard?

2024-08-14 19:07 UTC, EvanSimpson requested changes
Can we also rename gce-disk everywhere to compute-disk?
e.g. google-compute disk as the folder, compute-disk as the file name/ID?

2024-08-19 16:12 UTC, philshin-google commented
> Can we also rename gce-disk everywhere to compute-disk? e.g. google-compute disk as the folder, compute-disk as the file name/ID?

done!

2024-08-19 17:07 UTC, EvanSimpson requested changes

2024-08-19 17:07 UTC, EvanSimpson commented on dashboards/google-compute-disk/metadata.yaml
> +    This dashboard has charts displaying an inventory of GCE Disks, as well as Volume throughput and IOPS.
I think this needs an additional indent

```suggestion
      This dashboard has charts displaying an inventory of GCE Disks, Volume throughput, and IOPS.
```

2024-08-19 18:31 UTC, EvanSimpson approved these changes

2024-08-19 19:29 UTC, merged