Add Cloud Spanner dashboard
GoogleCloudPlatform/monitoring-dashboard-samples pull request #852
Opened 2024-10-17 16:52 UTC by justjohn

2024-10-17 20:30 UTC, EvanSimpson requested changes
This directory needs a metadata.yaml file

2024-10-21 15:18 UTC, justjohn commented
> This directory needs a metadata.yaml file

Added w/o the related integration for now.

2024-10-22 00:12 UTC, EvanSimpson requested changes

2024-10-22 00:12 UTC, EvanSimpson commented on dashboards/google-spanner/metadata.yaml
> +    display_name: VPN
```suggestion
    display_name: Cloud Spanner
```

2024-10-22 00:12 UTC, EvanSimpson approved these changes

2024-10-22 00:13 UTC, merged